import sys

files = [
    r'Engine\Core\Utility\UtilityFunctions.cpp',
    r'Engine\Effect\ParticleManager.cpp',
    r'Engine\GameObject\Object3D.cpp',
    r'Engine\GameObject\PrimitiveObject.cpp',
    r'Engine\Resource\Sprite\Sprite.cpp'
]

fixes = {
    '// メチEージに応じてゲーム固有E処琁E行う': '// メッセージに応じてゲーム固有の処理を行う',
    '// ウィンドウが破壊された': '// ウィンドウが破壊された',
    '// OSに応じて、アプリ固有E終亁E伝えめE': '// OSに応じて、アプリ固有の終了を伝える',
    '// 標準EメチEージ処琁E行う': '// 標準のメッセージ処理を行う',
    '// チEチE出力（従来の動作！E': '// デバッグ出力（従来の動作）',
    '// ログファイルを一度だけ作Eして使ぁEす（スレチEセーフ！E': '// ログファイルを一度だけ作成して使います（スレッドセーフ）',
    '// logs チEレクトリを作E': '// logs ディレクトリを作成',
    '// 現在の時刻を秒単位に丸める': '// 現在の時刻を秒単位に丸める',
    '// ローカルタイムゾーンに変換してフォーマット（Eコードと同じ書式を使用EE': '// ローカルタイムゾーンに変換してフォーマット（文字コードと同じ書式を使用）',
    '// ファイルパスを作Eして openE追記モード！E': '// ファイルパスを作成して open（追記モード）',
    '// 例外E無視してチEチE出力Eみ行うEログ失敗してもアプリが止まらなぁEぁEするEE': '// 例外は無視してデバッグ出力のみ行う（ログ失敗してもアプリが止まらないようにする）',
    '// 実際の書き込み': '// 実際の書き込み',
    '// 時刻を取得して、時刻を名前に入れたファイルを作E、EumpsチEレクトリ以下に出劁E': '// 時刻を取得して、時刻を名前に入れたファイルを作成、dumpsディレクトリ以下に出力',
    '// チEレクトリ作EE失敗しても続行！E': '// ディレクトリ作成（失敗しても続行）',
    '// ファイル名（秒単位！E': '// ファイル名（秒単位）',
    '// ログにパスをE劁E': '// ログにパスを出力',
    '// ファイル作E': '// ファイル作成',
    '// processId(exeID)とクラチEュ(例夁Eの発生したthreadIDを取征E': '// processId(exeID)とクラッシュ(例外)の発生したthreadIDを取得',
    '// 設定情報をE劁E': '// 設定情報を出力',
    '// DumpをE力。結果をログに残す': '// Dumpを出力。結果をログに残す',
    '// ほかに関連付けられてぁESEH例外ハンドラがあれE実行。通常プロセスを終亁Eる、E': '// ほかに関連付けられているSEH例外ハンドラがあれば実行。通常プロセスを終了する。',
    '// CompilerするShaderファイルへのパス': '// CompilerするShaderファイルへのパス',
    '// Compilerに使用するProfile': '// Compilerに使用するProfile',
    '// 初期化で生EしたもEめEつ': '// 初期化で生成したものを渡す',
    '// これからシェーダーをコンパイルする旨をログに出ぁE': '// これからシェーダーをコンパイルする旨をログに出す',
    '// あきらめなかったら止める': '// あきらめなかったら止める',
    '// 読み込んだファイルの冁Eを設定すめE': '// 読み込んだファイルの中身を設定する',
    'shaderSourceBuffer.Encoding = DXC_CP_UTF8;// UTF8の斁Eコードであることを通知': 'shaderSourceBuffer.Encoding = DXC_CP_UTF8;// UTF8の文字コードであることを通知',
    '*2.Compileする': '2.Compileする',
    'filePath.c_str(),         // コンパイル対象のhlslファイル吁E': 'filePath.c_str(),         // コンパイル対象のhlslファイル名',
    'L"-E", L"main",           // エントリーポイントE持E。基本皁Emain以外にはしなぁE': 'L"-E", L"main",           // エントリーポイントの指定。基本的にmain以外にはしない',
    'L"-T", profile,           // ShaderProfileの設宁E': 'L"-T", profile,           // ShaderProfileの設定',
    'L"-Zi", L"-Qembed_debug", // チEチE用の惁Eを埋め込む': 'L"-Zi", L"-Qembed_debug", // デバッグ用の情報を埋め込む',
    'L"-Od",                   // 最適化を外しておく': 'L"-Od",                   // 最適化を外しておく',
    'L"-Zpr",                  // メモリレイアウトE行優允E': 'L"-Zpr",                  // メモリレイアウトは行優先',
    'L"-HV", L"2021",          // ☁Eこれを追加EEHLSL2021ルールを適用してC++と同じ型名を使えるようにする': 'L"-HV", L"2021",          // ※これを追加：HLSL2021ルールを適用してC++と同じ型名を使えるようにする',
    '// 実際にShaderをコンパイルする': '// 実際にShaderをコンパイルする',
    '// コンパイラエラーではなくdxcが起動できなぁEどの致命皁Eエラー': '// コンパイラエラーではなくdxcが起動できないなどの致命的なエラー',
    '*3.警告EエラーがEてぁEぁE確誁E': '3.警告やエラーが出ているか確認',
    '// shaderErrorが作られてぁE、かつ中身の斁EEの長さが0ではなぁE合だけエラーとみなぁE': '// shaderErrorが作られており、かつ中身の文字列の長さが0ではない場合だけエラーとみなす',
    '// 警告Eエラー絶対ダメ': '// 警告やエラー絶対ダメ',
    '*4.Compile結果を受け取って返す': '4.Compile結果を受け取って返す',
    '// コンパイル結果から実行用のバイナリ部刁E取征E': '// コンパイル結果から実行用のバイナリ部分を取得',
    '// 成功押したログをEぁE': '// 成功したログを出す',
    '// もう使わなぁEソースを開放': '// もう使わないソースを開放',
    '// 実行用のバイナリを返却': '// 実行用のバイナリを返却',
    'assert(device != nullptr); // 安EチェチE': 'assert(device != nullptr); // 安全チェック',
    '// アチEEロード用のヒEプE設定！EPUからGPUにチEEタを送る用EE': '// アップロード用のヒープの設定（CPUからGPUにデータを送る用）',
    '// バッファリソースの設宁E': '// バッファリソースの設定',
    '// 実際にリソースEバチEァEを作E': '// 実際にリソース（バッファ）を作成',
    'D3D12_RESOURCE_STATE_COMMON, // 初期状態（読み取り用EE': 'D3D12_RESOURCE_STATE_COMMON, // 初期状態（読み取り用）',
    'return resource; // 作ったバチEァを返すEE': 'return resource; // 作ったバッファを返す',
    '// DescriptorHeapの作E関数': '// DescriptorHeapの作成関数',
    '// TextureチEEタを読む': '// Textureデータを読む',
    '// ファイルパス確認用のログ': '// ファイルパス確認用のログ',
    '// ☁EEの持E1EDDSファイルに対応すめE': '// 備考1：DDSファイルに対応する',
    '// .ddsで終わってぁEらDDSとして読み込む。sRGB惁Eが含まれてぁEのでフラグはNONE': '// .ddsで終わっていたらDDSとして読み込む。sRGB情報が含まれているのでフラグはNONE',
    '// それ以外E従来通りWICEENGやJPGなどEとして読み込む': '// それ以外は従来通りWIC（PNGやJPGなど）として読み込む',
    '// ☁EEの持E2E圧縮フォーマットか判定してミップEチEE生EをEける': '// 備考2：圧縮フォーマットか判定してミップマップ生成を避ける',
    '// 圧縮フォーマットならそのまま使ぁEEirectXTexが直接のミップEチEE生Eに非対応なためEE': '// 圧縮フォーマットならそのまま使う（DirectXTexが直接のミップマップ生成に非対応なため）',
    '// 非圧縮ならミチEEマップを作Eする': '// 非圧縮ならミップマップを作成する',
    'DirectX::TEX_FILTER_SRGB, 4, mipImages); // 第5引数の 0(MAX) めE4 など任意に変更可能': 'DirectX::TEX_FILTER_SRGB, 4, mipImages); // 第5引数の 0(MAX) や 4 など任意に変更可能',
    '// DirectX12のTextureResourceを作る': '// DirectX12のTextureResourceを作る',
    '// metadataをもとにResourceの設宁E': '// metadataをもとにResourceの設定',
    'resourceDesc.Width = UINT(metadata.width);// 横幁E': 'resourceDesc.Width = UINT(metadata.width);// 横幅',
    'resourceDesc.MipLevels = UINT(metadata.mipLevels);// mipmapの数': 'resourceDesc.MipLevels = UINT(metadata.mipLevels);// mipmapの数',
    'resourceDesc.DepthOrArraySize = UINT(metadata.arraySize);// 奥行き ro 配ETextureの配E数': 'resourceDesc.DepthOrArraySize = UINT(metadata.arraySize);// 奥行き or 配列Textureの配列数',
    'resourceDesc.Format = metadata.format;// TextureのFormat': 'resourceDesc.Format = metadata.format;// TextureのFormat',
    'resourceDesc.SampleDesc.Count = 1;// サンプリングカウンチE': 'resourceDesc.SampleDesc.Count = 1;// サンプリングカウント',
    'resourceDesc.Dimension = D3D12_RESOURCE_DIMENSION(metadata.dimension);// Textureの次允E、E次允E': 'resourceDesc.Dimension = D3D12_RESOURCE_DIMENSION(metadata.dimension);// Textureの次元（2次元）',
    '// 利用するHeapの設宁E': '// 利用するHeapの設定',
    'heapProperties.Type = D3D12_HEAP_TYPE_DEFAULT;// 細かい設定を行う': 'heapProperties.Type = D3D12_HEAP_TYPE_DEFAULT;// 細かい設定を行う',
    '// Resourceの生E': '// Resourceの生成',
    '&heapProperties,// Heapの設宁E': '&heapProperties,// Heapの設定',
    'D3D12_HEAP_FLAG_NONE,// Heapの特殊な設定。今回はなぁE': 'D3D12_HEAP_FLAG_NONE,// Heapの特殊な設定。今回はなし',
    '&resourceDesc,// Resourceの設宁E': '&resourceDesc,// Resourceの設定',
    'D3D12_RESOURCE_STATE_COPY_DEST,// 初回のResourceState、E': 'D3D12_RESOURCE_STATE_COPY_DEST,// 初回のResourceState',
    'nullptr,//Clear最適値。今回は使わなぁE': 'nullptr,//Clear最適値。今回は使わない',
    '// 戻り値を破損してはならなぁEEでこれを付けめE': '// 戻り値を破棄してはならないのでこれを付ける',
    '// TextureResouorceにチEEタを転送すめE': '// TextureResourceにデータを転送する',
    '// 読み込んだチEEタからDirectX12用のSubresourceの配Eを作E': '// 読み込んだデータからDirectX12用のSubresourceの配列を作成',
    '// IntermediateResourceに忁Eなサイズを計算すめE': '// IntermediateResourceに必要なサイズを計算する',
    '// 計算したサイズでIntermediateResourceを作る': '// 計算したサイズでIntermediateResourceを作る',
    '// チEEタ転送をコマンドに積E': '// データ転送をコマンドに積む',
    '// Tetureへの転送後E利用できるよう、D3D12_RESOURCE_STATE_COPY_DESTからD3D12_RESOURCE_STATE_GENERIC_READへResourceStateを変更する': '// Textureへの転送後に利用できるよう、D3D12_RESOURCE_STATE_COPY_DESTからD3D12_RESOURCE_STATE_GENERIC_READへResourceStateを変更する',
    '// 生EするResourceの設宁E': '// 生成するResourceの設定',
    'resourceDesc.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;// 2次允E': 'resourceDesc.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;// 2次元',
    '// 深層値のクリア設宁E': '// 深度値のクリア設定',
    'depthClearValue.Format = DXGI_FORMAT_D24_UNORM_S8_UINT;// フォーマットをResourceと合わせる': 'depthClearValue.Format = DXGI_FORMAT_D24_UNORM_S8_UINT;// フォーマットをResourceと合わせる',
    '// DescriptorHandleを取得すめECPU)': '// DescriptorHandleを取得する(CPU)',
    '// DescriptorHandleを取得すめEGPU)': '// DescriptorHandleを取得する(GPU)',
    '// 緯度の刁E数: 上から下へ何段に刁Eるか': '// 緯度の分割数: 上から下へ何段に分割するか',
    '// 経度の刁E数: 横に何E割するか（赤道E輪刁EみたいなイメージEE': '// 経度の分割数: 横に何分割するか（赤道の輪切りみたいなイメージ）',
    '// 頂点の生EE緯度方向にループ！E': '// 頂点の生成（緯度方向にループ）',
    'float theta = lat * float(M_PI) / float(latDiv); // 緯度の角度EE ~ πEE': 'float theta = lat * float(M_PI) / float(latDiv); // 緯度の角度（0 ~ π）',
    '// 経度方向にルーチE': '// 経度方向にループ',
    'float phi = lon * 2.0f * float(M_PI) / float(lonDiv); // 経度の角度EE ~ 2πEE': 'float phi = lon * 2.0f * float(M_PI) / float(lonDiv); // 経度の角度（0 ~ 2π）',
    '// 琁EEx, y, z座標を求めめE': '// 球面のx, y, z座標を求める',
    '// 頂点チEEタを作E': '// 頂点データを作成',
    'v.position = { radius * x, radius * y, radius * z, 1.0f }; // 琁EE表面上E点': 'v.position = { radius * x, radius * y, radius * z, 1.0f }; // 球の表面上の点',
    '// 三角形インチEクスの生EE頂点をつなぐ！E': '// 三角形インデックスの生成（頂点をつなぐ）',
    '// 現在の行E列から頂点の番号を計箁E': '// 現在の行・列から頂点の番号を計算',
    '// 二つの三角形を使って四角形を埋める': '// 二つの三角形を使って四角形を埋める',
    'indices.push_back(first);         // 左丁E': 'indices.push_back(first);         // 左下',
    'indices.push_back(first + 1);     // 右丁E': 'indices.push_back(first + 1);     // 右下',
    'indices.push_back(second);        // 左丁E': 'indices.push_back(second);        // 左上',
    'indices.push_back(second + 1);    // 右丁E': 'indices.push_back(second + 1);    // 右上',
    '// 1. ファイルの読み込み': '// 1. ファイルの読み込み',
    '// 賁Eにある通り、三角形化、巻き頁E転、UV反転を指宁E': '// 備考にある通り、三角形化、巻き順反転、UV反転を指定',
    '// 1. すべての面を三角形に変換EEirectXが理解できる形式にするEE': '// 1. すべての面を三角形に変換（DirectXが理解できる形式にする）',
    '// 2. V軸を反転EElTFなどの左下原点を、DirectX標準E左上原点に合わせるEE': '// 2. V軸を反転（glTFなどの左下原点を、DirectX標準の左上原点に合わせる）',
    '// 3. 右手系から左手系へ変換E軸の反転めEき頁EE調整をセチEで行うEE': '// 3. 右手系から左手系へ変換（Z軸の反転や巻き順の調整をセットで行う）',
    '// メチEュがなぁE合Eエラー': '// メッシュがない場合はエラー',
    '// 2. メチEュの解析（賁Eに基づき、EメチEュをループ！E': '// 2. メッシュの解析（備考に基づき、全メッシュをループ）',
    '// 法線とTexcoordがなぁEチEュは今回は非対応（賁EのassertEE': '// 法線とTexcoordがないメッシュは今回は非対応（備考のassert）',
    '// 頂点チEEタの解极E': '// 頂点データの解析',
    '// 左手系への変換E賁Eの通り、Xを反転EE': '// 左手系への変換（備考の通り、Xを反転）',
    '// インチEクスEEaceEE解析（賁EEIndexed描画に対応させるEE': '// インデックス(Face)の解析（備考のIndexed描画に対応させる）',
    'assert(face.mNumIndices == 3); // 三角形のみサポEチE': 'assert(face.mNumIndices == 3); // 三角形のみサポート',
    '// 3. マテリアルの解析（賁Eに基づき、DiffuseチEスチャを取得！E': '// 3. マテリアルの解析（備考に基づき、Diffuseテクスチャを取得）',
    'std::string line;//　ファイルから読んだ1行目を格納すめE': 'std::string line;//　ファイルから読んだ1行目を格納する',
    'std::ifstream file(directoryPath + "/" + filename);// ファイルを開ぁE': 'std::ifstream file(directoryPath + "/" + filename);// ファイルを開く',
    'assert(file.is_open());// 開けなかったら止める': 'assert(file.is_open());// 開けなかったら止める',
    '// identifierに応じたE琁E': '// identifierに応じた処理',
    '// 連結してファイルパスにする': '// 連結してファイルパスにする',
    '// ファイル入力ストリームのインスタンス': '// ファイル入力ストリームのインスタンス',
    '// ファイルオープン失敗を検Eする': '// ファイルオープン失敗を検出する',
    '/*.wavチEEタ読み込み': '/*.wavデータ読み込み',
    '// RIFFヘッダーの読み込み': '// RIFFヘッダーの読み込み',
    '// タイプがRIFFかチェチE': '// タイプがRIFFかチェック',
    '// タイプがWAVEかチェチE': '// タイプがWAVEかチェック',
    '// Formatチャンク読み込み': '// Formatチャンク読み込み',
    '// fmtチャンクを探すルーチE': '// fmtチャンクを探すループ',
    '// チャンクIDぁE"fmt " なめEbreak': '// チャンクIDが"fmt " ならbreak',
    '// それ以外ならスキチEE': '// それ以外ならスキップ',
    '// チャンク本体E読み込み': '// チャンク本体の読み込み',
    '// Dataチャンクの読み込み': '// Dataチャンクの読み込み',
    '// JUNKチャンクを検Eした場吁E': '// JUNKチャンクを検出した場合',
    '// 読み取り位置をJUNKチャンクの終わりまで進める': '// 読み取り位置をJUNKチャンクの終わりまで進める',
    '// 再読み込み': '// 再読み込み',
    '// DataチャンクのチEEタ部刁Eみ込み': '// Dataチャンクのデータ部分読み込み',
    '// waveファイルを閉じる': '// waveファイルを閉じる',
    '/*.読み込んだ音声チEEタをreturn': '/*.読み込んだ音声データをreturn',
    '// returnするための音声チEEタ': '// returnするための音声データ',
    '// バッファのメモリを解放': '// バッファのメモリを解放',
    '// 1. SourceReaderの作E': '// 1. SourceReaderの作成',
    '// 2. 出力形式をPCME解凍後E生データEに設宁E': '// 2. 出力形式をPCM（解凍後の生データ）に設定',
    '// 3. 最終的な波形フォーマットを取征E': '// 3. 最終的な波形フォーマットを取得',
    '// 4. 全てのサンプルを読み込んでバッファに格紁E': '// 4. 全てのサンプルを読み込んでバッファに格納',
    'CoTaskMemFree(pWfex); // MFが生成したフォーマット構造体を解放': 'CoTaskMemFree(pWfex); // MFが生成したフォーマット構造体を解放',
    '// ☁EEの持E1: RenderTargetとして利用可能にする特殊なフラグ': '// 備考1: RenderTargetとして利用可能にする特殊なフラグ',
    '// ☁EEの持E2: 当然VRAM上に作る (DEFAULT)': '// 備考2: 当然VRAM上に作る (DEFAULT)',
    '// クリア時E色を設定（レンダーターゲチE生E時にはこれが忁Eです！E': '// クリア時の色を設定（レンダーターゲット生成時にはこれが必要です）',
    '// --- 頂点座標E定義 ---': '// --- 頂点座標の定義 ---',
    '// --- インチEクスの定義EE側を向く頁E！E---': '// --- インデックスの定義（外側を向く順！）---',
    '// 吁E [0,1,2][2,1,3] のパターンで訁E6倁E': '// 例 [0,1,2][2,1,3] のパターンで計6個',
    
    '// --- 乱数生E器の準備 ---': '// --- 乱数生成器の準備 ---',
    '// 初期化時はリストをクリアするだけ（最初EパEチEクル0個！E': '// 初期化時はリストをクリアするだけ（最初はパーティクル0個！）',
    '// エミッタのチEォルト設宁E': '// エミッタのデフォルト設定',
    'emitter_.count = 3;           // 1回で3個EめE': 'emitter_.count = 3;           // 1回で3個',
    'emitter_.frequency = 0.5f;    // 0.5秒ごとに発甁E': 'emitter_.frequency = 0.5f;    // 0.5秒ごとに発生',
    'emitter_.frequencyTime = 0.0f;// タイマE初期匁E': 'emitter_.frequencyTime = 0.0f;// タイマー初期化',
    '// 刁EEE設定！E-1.0f EE1.0f の間E値をランダムに出ぁE': '// 分布の設定（-1.0f から 1.0f の間の値をランダムに出す）',
    '// 色用の乱数刁EE(0.0f EE1.0f)': '// 色用の乱数分布(0.0f から 1.0f)',
    '// 1. Instancingリソースの作E': '// 1. Instancingリソースの作成',
    '// 初期匁E(単位行E)': '// 初期化(単位行列)',
    '// 2. SRVの作E': '// 2. SRVの作成',
    '// ストライチE1要素のサイズ)めEParticleForGPU に合わせる': '// ストライド（1要素のサイズ）もParticleForGPU に合わせる',
    '// ハンドルの計箁E(持Eされたindexの場所を使ぁE': '// ハンドルの計算(指定されたindexの場所を使う)',
    '// 3. マテリアルの作E': '// 3. マテリアルの作成',
    '// materialResource_->Unmap(0, nullptr); // 書き続けるならUnmapしなぁE': '// materialResource_->Unmap(0, nullptr); // 書き続けるならUnmapしない',
    '// 4. チEスチャ読み込み': '// 4. テクスチャ読み込み',
    '// コマンドリストが忁EなのでParticleCommonから取得するか、TextureManager::Loadのタイミングを老Eる忁EがあるぁE': '// コマンドリストが必要なのでParticleCommonから取得するか、TextureManager::Loadのタイミングを考える必要がある',
    '// ここでは初期化時にコマンドリストを渡してぁEぁEめ、事前にロード済みであることを前提とするか、E': '// ここでは初期化時にコマンドリストを渡していないため、事前にロード済みであることを前提とするか、',
    '// InitializeにCommandListを渡すよぁE変更するのが良ぁEE': '// InitializeにCommandListを渡すように変更するのが良い',
    '// 今回は簡易的にロードE琁E呼ぶ (冁Eでロード済みならハンドルだけ返ってくる)': '// 今回は簡易的にロード処理を呼ぶ (内部でロード済みならハンドルだけ返ってくる)',
    '// +x方向に15m/s、篁Eは原点中忁E -1 ~ 1': '// +x方向に15m/s、ランダムは原点中心 -1 ~ 1',
    '// ランダムな移動Eクトル': '// ランダムな移動ベクトル',
    '// 位置Eエミッタの場所(translate) + ランダムなオフセチE': '// 位置はエミッタの場所(translate) + ランダムなオフセット',
    '// これにより「エミッタの場所から」パーチEクルがEるよぁEなりまぁE': '// これにより「エミッタの場所から」パーティクルが出るようになります',
    '// エミッタの位置を渡して生E': '// エミッタの位置を渡して生成',
    '// 刁EEE設宁E': '// 分布の設定',
    '// 値をランダムにセチE': '// 値をランダムにセット',
    '// Emitterの座標をぁEめE': '// Emitterの座標を決める',
    '// 賁Eの記述: ImGui::DragFloat3("EmitterTranslate", &emitter.transform.translate.x, 0.01f, -100.0f, 100.0f);': '// 元の記述: ImGui::DragFloat3("EmitterTranslate", &emitter.transform.translate.x, 0.01f, -100.0f, 100.0f);',
    '// ウィンドウが乱立しなぁEぁECollapsingHeader等で囲むのが一般皁Eすが、E': '// ウィンドウが乱立しないようCollapsingHeader等で囲むのが一般的ですが、',
    '// まずE賁E通りに実裁Eます、E': '// まずは元の通りに実装します。',
    '// (おまぁE 頻度もいじれると便利なので追加しておくと良ぁEしょぁE': '// (おまけ 頻度もいじれると便利なので追加しておくと良いでしょう)',
    '// ■ 追加: ビルボEドEON/OFF刁E替ぁE': '// ■ 追加: ビルボードのON/OFF切り替え',
    '// ☁Eこで ParticleCommon からカメラ行EをもらうEE': '// ここで ParticleCommon からカメラ行列をもらう',
    '// ビルボEド行Eの計算をフラグで刁Eさせる': '// ビルボード行列の計算をフラグで分岐させる',
    '// ONの場吁E カメラの向きに合わせて回転を作る (既存E処琁E': '// ONの場合 カメラの向きに合わせて回転を作る (既存の処理)',
    '// OFFの場吁E 回転なぁE(単位行E)': '// OFFの場合 回転なし(単位行列)',
    '// ※もしパEチEクル個別の回転(it->transform.rotate)を使ぁEぁE合E': '// ※もしパーティクル個別の回転(it->transform.rotate)を使いたい場合',
    '//   ここで個別に計算する忁Eがありますが、まずE「向かなぁE状態にしまぁE': '//   ここで個別に計算する必要がありますが、まずは「向かない」状態にします',
    '// 2. 全パEチEクルをループしてGPUバッファに書き込む': '// 2. 全パーティクルをループしてGPUバッファに書き込む',
    '// 行E計箁E': '// 行列計算',
    '// チEEタセチE': '// データセット',
    
    'model_ = model; // 共有されてぁEモチEをセチE': 'model_ = model; // 共有されているモデルをセット',
    '// マテリアルが透EにならなぁEぁE初期値を設定すめE': '// マテリアルが透明にならないよう初期値を設定する',
    'material_.color = {1.0f, 1.0f, 1.0f, 1.0f};                    // 白色で不透E (RGBA)': 'material_.color = {1.0f, 1.0f, 1.0f, 1.0f};                    // 白色で不透明 (RGBA)',
    'material_.lightingType = 1;                                    // ライチEング有効': 'material_.lightingType = 1;                                    // ライティング有効',
    'material_.uvTransform = TransformFunctions::MakeIdentity4x4(); // 以前作った単位行Eを返す関数': 'material_.uvTransform = TransformFunctions::MakeIdentity4x4(); // 以前作った単位行列を返す関数',
    '// マテリアルと座標変換リソースの作EEE刁EE刁Eけ！E': '// マテリアルと座標変換リソースの作成（1つ分だけ！）',
    '// ☁Eマネージャから最新のカメラ惁EをゲチEEE': '// マネージャから最新のカメラ情報をゲット',
    '// ☁Eマネージャから新のカメラ惁EをゲチEEE': '// マネージャから最新のカメラ情報をゲット',
    '// 自身のワールド行E作E': '// 自身のワールド行列作成',
    '// モチE側のローカル行Eを除外（スキニング対応EためEE': '// モデル側のローカル行列を除外（スキニング対応のため）',
    '// ☁Eここを修正EE頁EE World * View * Projection': '// ※ここを修正：順は World * View * Projection',
    '// ☁E追加E法線用行Eの計算（これがなぁEライチEングが真っ黒になります！E': '// ※追加：法線用行列の計算（これがないとライティングが真っ黒になります！）',
    '// 軌跡用履歴の保孁E': '// 軌跡用履歴の保存',

    '// ゴースト描画用リソースの初期匁E': '// ゴースト描画用リソースの初期化',
    '// カメラのワールド行EEビュー行Eの送EEEを取征E': '// カメラのワールド行列(ビュー行列の逆行列)を取得',
    '// 回転成Eのみを抽出してビルボEド行Eとする': '// 回転成分のみを抽出してビルボード行列とする',
    '// 回転行Eの作E (XYZの頁E合E)': '// 回転行列の作成 (XYZの順で合成)',
    '// ビルボEドが有効な場合E、ビルボEド回転を適用した後にローカル回転を適用する': '// ビルボードが有効な場合、ビルボード回転を適用した後にローカル回転を適用する',

    '// 破棁EれるときにリストからE刁E削除': '// 破棄されるときにリストから自分を削除',
    '// ☁EこでCommonに自刁E登録EE': '// ここでCommonに自分を登録！',
    '// マテリアルリソース作E': '// マテリアルリソース作成',
    '// 行E用のバッファリソースを作E': '// 行列用のバッファリソースを作成',
    '// 書き込み用のポインタを紐付けめE': '// 書き込み用のポインタを紐付ける',
    '// 初期値設宁E': '// 初期値設定',
    '// チEスチャサイズを取得（Eり抜き計算用EE': '// テクスチャサイズを取得（切り抜き計算用）',
    'texSize_ = texBaseSize_; // チEォルトE全篁E': 'texSize_ = texBaseSize_; // デフォルトは全範囲',
    '// 忁EならここでUVアニメーション処琁Eど': '// 必要ならここでUVアニメーション処理など',
}

def guess_string(text):
    try:
        return text.encode('cp932', errors='replace').decode('utf-8', errors='ignore')
    except:
        return text

count = 0
for f_path in files:
    with open(f_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    for i, line in enumerate(lines):
        guessed = guess_string(line)
        stripped_guessed = guessed.strip()
        for k, v in fixes.items():
            if k in stripped_guessed:
                new_line = guessed.replace(k, v)
                lines[i] = new_line
                count += 1
                break

    with open(f_path, 'w', encoding='utf-8') as f:
        f.write('\ufeff')
        for line in lines:
            if line.startswith('\ufeff'):
                line = line[1:]
            f.write(line)
